void menu_init(edit_data *ed);
void menu_term();
void menu_toggle();
void menu_ctxpopup_register(Evas_Object *ctxpopup);
void menu_ctxpopup_unregister(Evas_Object *ctxpopup);
void menu_edc_new();
void menu_edc_save();
void menu_edc_load();
void menu_exit();
void menu_about();
void menu_setting();
int menu_activated_get();
void menu_activate_request();
void menu_deactivate_request();
